better, more Windows friendly solution to creating a temporary directory
The Windows error with the previous implementation was:

Traceback (most recent call last):
  File "C:\Users\Administrator\git\bcolz\bcolz\tests\test_ctable.py", line 437,
  in test_add_new_column_ondisk_other_carr
  ay_rootdir
      os.remove(fn)
      WindowsError: [Error 32] The process cannot access the file because it is
      being used by another process: 'c:\\users\\adm
      ini~1\\appdata\\local\\temp\\2\\tmpzbzpj1'